secure-device-onboard/iot-platform-sdk

- README.md
Replacing the Iot-Platform-SDK's document placeholder location with the
appropriate URL.
> Update the document repository link in README

- Jenkinsfile.yml
Added archive artifacts step to jenkins file to pull the binaries of iot-platform-sdk in jenkins
Signed-off-by: Mareddy, Deepthi <deepthix.mareddy@intel.com>
> Update jenkins file to archive the binaries of iot-platform-sdk

- build/Dockerfile
- build/README.md
- build/build.sh
- build/docker-compose.yml
1. http typo mistake on line 7.
2. Removed all trailing whitespaces.
> Minor changes to `Ubuntu Docker Scripts for Building IOT-platform-SDK`

- ocs/fsimpl/pom.xml
- ocs/fsimpl/src/main/java/org/sdo/iotplatformsdk/ocs/fsimpl/fs/FsPropertiesLoader.java
- ops/restimpl/pom.xml
- ops/restimpl/src/main/java/org/sdo/iotplatformsdk/ops/opsimpl/OpsPropertiesLoader.java
- pom.xml
- to0scheduler/to0serviceimpl/pom.xml
- to0scheduler/to0serviceimpl/src/main/java/org/sdo/iotplatformsdk/to0scheduler/to0service/To0PropertiesLoader.java
Fix for "https://github.com/secure-device-onboard/iot-platform-sdk/issues/16"
Updating to use Apache Commons configuration to load properties, instead
of using Java's native Properties and System classes.
> Fix for Issue #16: Variable interpolation failure

- Jenkinsfile.yml
Added stage to run smoke test on iot-platform-sdk binaries with all
other SDO components.
Signed-off-by: Mareddy, Deepthi <depthix.mareddy@intel.com>
> Updated Jenkinsfile to run smoke tests

- README.md
Signed-off-by: Tom Barnes <thomas.j.barnes@intel.com>
> Update demo readme files with -not for production- note

- Jenkinsfile.yml
Updated smoke test goals from test to verify.
Signed-off-by: Mareddy, Deepthi <deepthix.mareddy@intel.com>
> Run smoke tests using verify goal instead of test

- pom.xml
Updating the third party library versions.
> Updating versions of used third party libraries

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Rolling version to 1.9, from 1.9-SNAPSHOT.
> Version roll to 1.9

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
> Version roll-over to 1.10-SNAPSHOT

- ops/epid/src/main/java/org/sdo/iotplatformsdk/ops/epid/EpidConstants.java
- ops/libops/src/main/java/org/sdo/iotplatformsdk/ops/to2library/Message44Handler.java
Adding check for AppId against a pre-defined list of values.
> Add appId verification check

- README.md
> Update README file for formatting fixes

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Rolling version to 1.10 Release, from 1.10-SNAPSHOT.
> Roll version to 1.10 Release

- pom.xml
> Update version for third-party components

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version roll-over to 1.10.1-SNAPSHOT
> Version roll-over to 1.10.1-SNAPSHOT

- build/Dockerfile
- build/build.sh
- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version roll-over to 1.10.1 Release.
> Version roll-over to 1.10.1 Release

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
> Prepare for 1.10.2 development

- demo/ocs/Dockerfile
- demo/ops/Dockerfile
- demo/to0scheduler/Dockerfile
> Update docker containers with latest packages

- README.md
- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/Dockerfile
- demo/ocs/ocs.env
- demo/ops/Dockerfile
- demo/ops/ops.env
- demo/to0scheduler/Dockerfile
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
> Roll version for 1.10.2 release

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover for 1.10.3 Development.
> Version rollover for 1.10.3 Development

- NOTICE
- NOTICES/JUNIT4-NOTICE
- ops/restimpl/pom.xml
- pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Upgrading to the latest spring-boot version.
spring-boot-starter:2.3.11.RELEASE => spring-boot-starter:2.5.4
> Upgrading to the latest spring-boot version

- pom.xml
Upgrading spring boot version.
> Upgrading spring boot version

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Roll version to 1.10.3 RELEASE.
> Roll version to 1.10.3 RELEASE

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version roll over to 1.10.4-SNAPSHOT
> Version roll over to 1.10.4-SNAPSHOT

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover to 1.10.4 Release.
> Version rollover to 1.10.4 Release

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover to 1.10.5-SNAPSHOT.
> Version rollover to 1.10.5-SNAPSHOT

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover to 1.10.5 Release.
> Version rollover to 1.10.5 Release

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover to 1.10.6-SNAPSHOT.
> Version rollover to 1.10.6-SNAPSHOT

- pom.xml
Upgrading dependencies to latest version.
> Upgrading dependencies to latest version

- README.md
- demo/ops/ops.env
- scripts/onDieCache.py
onDie fixes for IOT-PLATFORM-SDK.
Signed-off-by: Anapareddy, Sai Anudeep <sai.anudeep.anapareddy@intel.com>
> onDie fixes for IOT-PLATFORM-SDK

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover to 1.10.6 Release.
> Version rollover to 1.10.6 Release

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover to 1.10.7-SNAPSHOT.
> Version rollover to 1.10.7-SNAPSHOT

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover to 1.10.7 Release.
> Version rollover to 1.10.7 Release

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover to 1.10.8 SNAPSHOT.
> Version rollover to 1.10.8 SNAPSHOT

- README.md
- build/README.md
Updating Docker version in README.
> Updating Docker version in README

- common/pom.xml
- common/protocol/pom.xml
- common/rest/pom.xml
- demo/docker-compose.yaml
- demo/ocs/ocs.env
- demo/ops/ops.env
- demo/to0scheduler/to0scheduler.env
- ocs/fsimpl/pom.xml
- ocs/libocs/pom.xml
- ocs/pom.xml
- ops/epid/pom.xml
- ops/libops/pom.xml
- ops/pom.xml
- ops/restimpl/pom.xml
- ops/serviceinfo/pom.xml
- pom.xml
- to0scheduler/libto0/pom.xml
- to0scheduler/pom.xml
- to0scheduler/to0serviceimpl/pom.xml
Version rollover to 1.10.8 Release.
> Version rollover to 1.10.8 Release

- README.md
Updating EOL disclaimer in README.
> Updating EOL disclaimer in README
